config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'calls#index', as: :authenticated_root
      resources :calls

      resources :clients do
        resources :calls
      end
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :client

  enum reason: {
    Requerimiento: 'Requerimiento',
    Reclamo: 'Reclamo',
    Consulta: 'Consulta'
  }, _default: 'Consulta'

  validates :reason, inclusion: { in: %w[Reclamo Consulta Requerimiento] }

  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    client_id: 'A',
    reason: 'B',
    detail: 'C'
  }

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :calls, dependent: :destroy
  validates :name, presence: true
  validates :phone, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /calls or /calls.json
  def index
    @consulta = params[:buscar]

    if @consulta.present?
      @pagy, @calls = pagy(Call.search_full_text(@consulta))
    else
      if params[:client_id] != nil
        @client = Client.find(params[:client_id])
        @pagy,@calls = pagy(@client.calls)
      else
          @pagy, @calls = pagy(Call.all)
      end
    end

  end

  # GET /calls/1 or /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls or /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to call_url(@call), notice: "Call was successfully created." }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1 or /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to call_url(@call), notice: "Call was successfully updated." }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1 or /calls/1.json
  def destroy
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url, notice: "Call was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def call_params
      params.require(:call).permit(:reason, :client_id, :detail)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /clients or /clients.json
  def index
    @pagy, @clients = pagy(Client.all)
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  require 'pagy/extras/bootstrap'

  Pagy::DEFAULT[:items] = 10        # items per page

end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/calls/_call.html.erb
<div id="<%= dom_id call %>">
  <p>
    <strong>Reason:</strong>
    <%= call.reason %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= call.client_id %>
  </p>

  <p>
    <strong>Detail:</strong>
    <%= call.detail %>
  </p>

</div>

app/views/calls/_form.html.erb
<%= form_with(model: call, class: "form") do |form| %>
  <% if call.errors.any? %>
    <div class="alert alert-danger">
      <h2 class="my-3"><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :reason, "Razón", class: "form-label" %>
    <%= form.select :reason, Call.reasons.keys, { selected: "Consulta" }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :client_id, "Cliente", class: "form-label" %>
    <% if params[:client_id].nil? %>
      <%= form.collection_select :client_id, Client.all, :id, :name, { include_blank: true }, class: "form-select" %>
    <% else %>
      <%= form.collection_select :client_id, Client.all, :id, :name, { selected: params[:client_id] }, class: "form-select" %>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :detail, "Detalle", class: "form-label" %>
    <%= form.text_area :detail, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "Show this call", @call %> |
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/index.html.erb
<h1 class="my-3">Llamadas</h1>
<div id="clients">
  <div class="row">
    <div class="col-3">
      <%= link_to "Nuevo Llamado", new_call_path, class:"btn btn-lg w-100 btn-success" %>
    </div>
    <div class="col-9">
      <%= form_with url: calls_path, method: :get do |form| %>
        <!-- Cuadro de búsqueda-->
        <div class="card mb-2">
          <div class="card-body">
            <div class="input-group">
              <%= form.text_field :buscar, class: "form-control", placeholder: "Buscar Publicación", value: @consulta %>
              <%= form.submit 'Buscar', class: "btn btn-outline-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Client</th>
          <th scope="col">Razón</th>
          <th scope="col">Detalle</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @calls.each do |call| %>
          <tr class="">
            <td> <%= call.client.name %> </td>
            <td> <%= call.reason %> </td>
            <td> <%= call.detail %> </td>
            <td>
              <div class="btn-group" role="group" aria-label="Basic mixed styles example">
               <!--<%= button_to "Eliminar", call, method: :delete, class:"btn btn-danger" %>-->
                <%= link_to "Editar", edit_call_path(call.id), class:"btn btn-warning" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @call %>

<div>
  <%= link_to "Edit this call", edit_call_path(@call) %> |
  <%= link_to "Back to calls", calls_path %>

  <%= button_to "Destroy this call", @call, method: :delete %>
</div>

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= client.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client, class: "form") do |form| %>
  <% if client.errors.any? %>
    <div class="alert alert-danger">
      <h2 class="my-3"><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "Nombre", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, "Telefono", class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<h1 class="my-3">Clientes</h1>
<div id="clients">
  <div class="row">
    <div class="col-3">
      <%= link_to "Nuevo cliente", new_client_path, class:"btn btn-lg w-100 btn-success" %>
    </div>
    <div class="col-9">
      <%= form_with url: calls_path, method: :get do |form| %>
        <!-- Cuadro de búsqueda-->
        <div class="card mb-2">
          <div class="card-body">
            <div class="input-group">
              <%= form.text_field :buscar, class: "form-control", placeholder: "Buscar Publicación", value: @consulta %>
              <%= form.submit 'Buscar', class: "btn btn-outline-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table text-center">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Email</th>
          <th scope="col">Telefono</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <tr class="">
            <td> <%= client.name %> </td>
            <td> <%= client.email %> </td>
            <td> <%= client.phone %> </td>
            <td>
              <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                <%= link_to client_calls_path(client.id) do %>
                  <i class="fa-solid fa-phone-volume fa-2xl mx-2"></i>
                <% end %>
                <%= link_to new_client_call_path(client.id) do %>
                  <i class="fas fa-phone fa-2xl mx-2"></i>
                <% end %>
                <%= button_to "Eliminar", client, method: :delete, class:"btn btn-danger" %>
                <%= link_to "Editar", edit_client_path(client.id), class:"btn btn-warning" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamenCertificacionAdolfoalvarez</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-warning">
  <div class="container">
    <a class="navbar-brand" href="<%= calls_path %>">PREPARACIÓN EXAMEN</a>
    <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <ul class="navbar-nav me-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="<%= calls_path %>" aria-current="page">Inicio <span class="visually-hidden">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= calls_path %>">Llamadas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= clients_path %>">Clientes</a>
        </li>
        <% if !user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_session_path %>">Ingresar</a>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
            <div class="dropdown-menu" aria-labelledby="dropdownId">
              <%= button_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% if notice.present? %>
  <p class="notice alert alert-warning" role="alert"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert alert-danger" role="alert"><%= alert  %></p>
<% end %>

app/views/shared/_popup.html.erb
<!-- Button trigger modal -->
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
  const myModal = document.getElementById('myModal')
  const myInput = document.getElementById('myInput')

  myModal.addEventListener('shown.bs.modal', () => {
    myInput.focus()
  })
</script>